pipeline {
    agent {
        label "demoAgent"
    }

    stages {
        stage('git') {
            steps {
                git 'https://github.com/redbeanmk765/SeleniumExample.git'
            }
            
        }
        stage('mvn') {
            steps {
                sh "mvn -Dmaven.test.failure.ignore=true clean test"
            }   
        }
    }
}
